FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock

COPY ./packages.json ./packages.json
COPY ./tsconfig.json ./tsconfig.json

COPY ./apps/frontend ./apps/frontend

RUN bun install
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build 

EXPOSE 3000
 
CMD ["bun", "run", "start:web"]
